# Generated by Django 5.1.3 on 2024-11-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customerreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeatureProduct',
        ),
    ]
