# Generated by Django 5.1.3 on 2024-12-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
